/*
 * CSCE 4444
 * 
 * 
 */
package GUI;

import Listener.AlertPanelListener;


//*************************************************************
//Creates Alert Message panels that are Added to the Alert Panel
//*************************************************************
public class AlertMessages extends javax.swing.JPanel
{
    AlertPanelListener alertPanelListener;
    /**
     * Creates new form AlertMessages
     */

    
    
    public AlertMessages(String message, AlertPanelListener alertPanelListener)
    {
        initComponents();
        this.alertPanelListener = alertPanelListener;
        alertMessage.setText(message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        alertMessage = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        alertMessage.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        alertMessage.setForeground(new java.awt.Color(255, 255, 0));
        alertMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alertMessage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        alertMessage.setMaximumSize(new java.awt.Dimension(388, 43));
        alertMessage.setMinimumSize(new java.awt.Dimension(388, 43));
        alertMessage.setPreferredSize(new java.awt.Dimension(388, 43));
        alertMessage.setSize(new java.awt.Dimension(388, 43));
        alertMessage.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                alertMessageMouseClicked(evt);
            }
        });
        add(alertMessage);
    }// </editor-fold>//GEN-END:initComponents

    private void alertMessageMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_alertMessageMouseClicked
    {//GEN-HEADEREND:event_alertMessageMouseClicked
       alertPanelListener.removeAlert(alertMessage.getText());
    }//GEN-LAST:event_alertMessageMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertMessage;
    // End of variables declaration//GEN-END:variables
}
