/*
 * CSCE 4444
 * 
 * 
 */
package GUI;

import Listener.AlertPanelListener;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

//*************************************************************
//This panel displays any alerts that are sent from the POS
//*************************************************************
public class Alerts extends javax.swing.JPanel
{
    ArrayList<String> messages;
    JPanel infoPanel;
    
    AlertPanelListener alertPanelListener = new AlertPanelListener()
    {
        @Override
        public void removeAlert(String message)
        {
            
            //Remove all alerts
            removeAll();
            repaint();
            revalidate();
            
            //Repopulate the alert messages
            repopulateAlerts(messages, message);
            
            //Update the Alert panel
            repaint();
            revalidate();
            
        }
    };
    
    
    public Alerts(ArrayList<String> messages, JPanel infoPanel)
    {
        initComponents();
        this.messages = messages;
        this.infoPanel = infoPanel;
        
        infoPanel.removeAll();
        infoPanel.repaint();
        infoPanel.revalidate();
        
        
        for(String s : messages)
        {
            add(new AlertMessages(s, alertPanelListener));
        }
        repaint();
        revalidate();
    }

    //Removes selected alert from the alert panel
    public void repopulateAlerts(ArrayList<String> messages, String message)
    {
        //Iterator for the massages array. 
        //This prevents a discovered concurrancy issue
        Iterator<String> iter = messages.iterator();

        //Look for the alert that was selected in the messages array
        //When found, remove it from the array
        while (iter.hasNext()) 
        {
            String str = iter.next();

            if (str.equals(message))
                iter.remove();
        }
       
        //Repopulate the alert messages 
        for(String s : messages)
        {
            add(new AlertMessages(s, alertPanelListener));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(388, 347));
        setSize(new java.awt.Dimension(388, 347));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
