/*
 * CSCE 4444
 * 
 * 
 */
package GUI;

import Food.Order;
import Listener.OrderItemDetailsListener;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class AssignedTables extends javax.swing.JPanel
{
    Order [] orders;
    JPanel infoPanel;

    /**
     * Creates new form assignedTables
     */
    public AssignedTables(Order [] orders, JPanel infoPanel)
    {
        initComponents();
        setSize(380, 340);
        this.orders = orders;
        this.infoPanel = infoPanel;
        
        infoPanel.removeAll();
        infoPanel.repaint();
        infoPanel.revalidate();
        
        
        displayTables();
    }
    
    public void displayTables()
    {
        for(int i = 0; i < 16; i++)
        {
            if(orders[i] != null)
            {
                add(new TableNumber((i+1)));
            }
        }
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
