/*
 * CSCE 4444
 * 
 * 
 */
package GUI;

import Food.Order;
import java.awt.Color;
import javax.swing.JLabel;

public class AssignedTables extends javax.swing.JPanel
{
    Order [] orders;

    /**
     * Creates new form assignedTables
     */
    public AssignedTables(Order [] orders)
    {
        initComponents();
        setSize(380, 340);
        this.orders = orders;
        displayTables();
    }
    
    public void displayTables()
    {
        for(int i = 0; i < 16; i++)
        {
            if(orders[i] != null)
            {
                JLabel jLabel = new JLabel("Table " + (i+1));
                jLabel.setForeground(Color.YELLOW);
                jLabel.setFont (jLabel.getFont ().deriveFont (24.0f));
                add(jLabel);
            }
        }
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
