/*
 * CSCE 4444
 * 
 * 
 */
package GUI;

import Listener.MessageListener;
import waiter.Waiter;



public class Frame extends javax.swing.JFrame implements Runnable
{

    Waiter waiter;
    /**
     * Creates new form Frame
     */

    public Frame(Waiter waiter)
    {
        //Crate Frame
        initComponents();
        setSize(400, 520);
        setLocation(1030, 0);
        
        this.waiter = waiter;//give the waiter object to the GUI
        
        //Create and add MainPanel
        MainPanel mainPanel = new MainPanel(waiter);
        mainPanel.setSize(400, 500);
        add(mainPanel);
        
        setVisible(true);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void run(){}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
