/*
 * CSCE 4444
 * 
 * 
 */
package GUI;

import Listener.Navigator;
import javax.swing.JPanel;
import waiter.Waiter;

public class MainPanel extends javax.swing.JPanel 
{

    Waiter waiter;
    /**
     * Creates new form MainPanel
     */
    public MainPanel(Waiter waiter)
    {
        initComponents();
        setSize(400, 500);
        
        this.waiter = waiter;
    }
    
    Navigator navigator = new Navigator()
    {
        void swapPanel(JPanel newPanel)
        {
            infoPanel.add(newPanel);
            infoPanel.repaint();
            infoPanel.revalidate();
        }
        
        @Override
        public void goToAssignedTables()
        {
            swapPanel(new AssignedTables(waiter.getOrders()));
        }

        @Override
        public void goToModifyOrder()
        {
            swapPanel(new ModifyOrder(waiter.getOrders()));
        }
    
    };
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel4 = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        assignedTables = new javax.swing.JLabel();
        modifyOrder = new javax.swing.JLabel();
        paymentOptions = new javax.swing.JLabel();
        notificationPanel = new javax.swing.JPanel();
        notification = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();

        jLabel4.setText("jLabel4");

        setBackground(new java.awt.Color(153, 0, 0));
        setPreferredSize(new java.awt.Dimension(400, 500));
        setSize(new java.awt.Dimension(400, 5000));

        buttonPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        buttonPanel.setOpaque(false);
        buttonPanel.setLayout(new java.awt.GridLayout(1, 0));

        assignedTables.setForeground(new java.awt.Color(255, 255, 0));
        assignedTables.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        assignedTables.setText("ASSIGNED TABLES");
        assignedTables.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        assignedTables.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                assignedTablesMouseClicked(evt);
            }
        });
        buttonPanel.add(assignedTables);

        modifyOrder.setForeground(new java.awt.Color(255, 255, 0));
        modifyOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modifyOrder.setText("MODIFY ORDER");
        modifyOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        modifyOrder.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                modifyOrderMouseClicked(evt);
            }
        });
        buttonPanel.add(modifyOrder);

        paymentOptions.setForeground(new java.awt.Color(255, 255, 0));
        paymentOptions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paymentOptions.setText("PAYMENT OPTIONS");
        paymentOptions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        buttonPanel.add(paymentOptions);

        notificationPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));
        notificationPanel.setOpaque(false);

        javax.swing.GroupLayout notificationPanelLayout = new javax.swing.GroupLayout(notificationPanel);
        notificationPanel.setLayout(notificationPanelLayout);
        notificationPanelLayout.setHorizontalGroup(
            notificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(notification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        notificationPanelLayout.setVerticalGroup(
            notificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(notification, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        infoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));
        infoPanel.setOpaque(false);
        infoPanel.setPreferredSize(new java.awt.Dimension(388, 347));
        infoPanel.setSize(new java.awt.Dimension(388, 347));

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(notificationPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(notificationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignedTablesMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_assignedTablesMouseClicked
    {//GEN-HEADEREND:event_assignedTablesMouseClicked
       navigator.goToAssignedTables();
    }//GEN-LAST:event_assignedTablesMouseClicked

    private void modifyOrderMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_modifyOrderMouseClicked
    {//GEN-HEADEREND:event_modifyOrderMouseClicked
        navigator.goToModifyOrder();
    }//GEN-LAST:event_modifyOrderMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assignedTables;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel modifyOrder;
    private javax.swing.JLabel notification;
    private javax.swing.JPanel notificationPanel;
    private javax.swing.JLabel paymentOptions;
    // End of variables declaration//GEN-END:variables
}
