/*
 * CSCE 4444
 * 
 * 
 */
package GUI;

import Food.Food;
import Food.Order;
import Listener.OrderItemDetailsListener;
import java.awt.Color;
import javax.swing.JLabel;

public class ModifyOrder extends javax.swing.JPanel
{
    Order [] orders;

    /**
     * Creates new form ModifyOrder
     */
    public ModifyOrder(Order [] orders)
    {
        initComponents();
        this.orders = orders;
        displayTables();
    }
    
    OrderItemDetailsListener listener = new OrderItemDetailsListener()
    {
        @Override
        public void modifyItem(Food item)
        {
            
        }

        @Override
        public void recallItem()
        {
            
        }
    };

    public void displayTables()
    {
        for(int i = 0; i < 16; i++)
        {
            if(orders[i] != null)
            {
                //add(new TableNumber(orders[i], listener, (i+1)));
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
