/*
 * CSCE 4444
 * 
 * 
 */
package GUI;

import Food.Food;
import Food.Order;

import Listener.OrderItemDetailsListener;

public class TableNumber extends javax.swing.JPanel
{
    OrderItemDetailsListener listener;
    int tableNum;
    Food item;
    /**
     * Creates new form TableNumber
     */
    public TableNumber(int tableNum)
    {
        initComponents();
        this.tableNum = tableNum;
        tableNumber.setText("Table " + tableNum);
        
    }
    public TableNumber(Food item, OrderItemDetailsListener listener, int tableNum)
    {
        initComponents();
        this.item = item;
        this.listener = listener;
        this.tableNum = tableNum;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        tableNumber = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.GridLayout());

        tableNumber.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        tableNumber.setForeground(new java.awt.Color(255, 255, 0));
        tableNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tableNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        tableNumber.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tableNumberMouseClicked(evt);
            }
        });
        add(tableNumber);
    }// </editor-fold>//GEN-END:initComponents

    private void tableNumberMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tableNumberMouseClicked
    {//GEN-HEADEREND:event_tableNumberMouseClicked
        if(listener != null)
        {
            listener.modifyItem(item);
        }
    }//GEN-LAST:event_tableNumberMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel tableNumber;
    // End of variables declaration//GEN-END:variables
}
